## NumPy ufunc (Universal Functions)

### What is a ufunc?

- ufunc stands for Universal Function.
- It performs operations on every element of a NumPy array.
- ufuncs are fast and optimized.

### Benefits

- Faster than Python loops.
- Less code.
- Better performance.
- Easy array calculations.

### Common ufuncs

```python
np.add()
np.subtract()
np.multiply()
np.divide()
np.sqrt()
np.power()
np.sin()
np.cos()
```

### Create Your Own ufunc

```python
np.frompyfunc(function, inputs, outputs)
```

### Best Practice

- Prefer NumPy ufuncs instead of manual loops for array operations.

In [ ]:
import numpy as np

# ==========================================
# Create Arrays
# ==========================================

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# ==========================================
# NumPy ufunc Examples
# ==========================================

print("Addition:")
print(np.add(arr1, arr2))

print("\nSubtraction:")
print(np.subtract(arr1, arr2))

print("\nMultiplication:")
print(np.multiply(arr1, arr2))

print("\nDivision:")
print(np.divide(arr1, arr2))

print("\nPower:")
print(np.power(arr1, 2))

Addition:
[11 22 33]

Subtraction:
[ 9 18 27]

Multiplication:
[10 40 90]

Division:
[10. 10. 10.]

Power:
[100 400 900]


## Create Your Own NumPy ufunc

### What is `np.frompyfunc()`?

- Converts a normal Python function into a NumPy ufunc.
- The created ufunc can work on NumPy arrays element by element.

### Syntax

```python
np.frompyfunc(function, inputs, outputs)
```

### Parameters

- `function` → Python function
- `inputs` → Number of input arguments
- `outputs` → Number of returned values

### Example

```python
def add(x, y):
    return x + y

myadd = np.frompyfunc(add, 2, 1)
```

### Check ufunc

```python
type(myadd)
```

### Best Practice

- Use `np.frompyfunc()` when you want to apply your own Python function to NumPy arrays.

In [ ]:
import numpy as np

# ==========================================
# Example 1: Create a ufunc
# ==========================================

def add(x, y):
    return x + y

myadd = np.frompyfunc(add, 2, 1)

result = myadd([1, 2, 3], [4, 5, 6])

print("Addition:")
print(result)

# ==========================================
# Example 2: Single Input Function
# ==========================================

def square(x):
    return x * x

mysquare = np.frompyfunc(square, 1, 1)

print("\nSquare:")
print(mysquare([2, 3, 4]))

# ==========================================
# Check the Type
# ==========================================

print("\nType of myadd:")
print(type(myadd))

<ufunc 'add (vectorized)'>
Addition:
[5 7 9]

Square:
[4 9 16]

Type of myadd:
<class 'numpy.ufunc'>


## NumPy ufunc Simple Arithmetic

### What are Arithmetic ufuncs?

- Perform arithmetic operations on NumPy arrays.
- Work element by element.
- Faster than Python loops.

### Arithmetic Functions

- `np.add()` → Addition
- `np.subtract()` → Subtraction
- `np.multiply()` → Multiplication
- `np.divide()` → Division
- `np.power()` → Power
- `np.mod()` → Modulus (Remainder)
- `np.remainder()` → Same as `mod()`
- `np.divmod()` → Quotient and Remainder
- `np.absolute()` → Absolute Value

### Best Practice

- Use NumPy arithmetic ufuncs instead of manual loops.
- Arrays should have compatible shapes.

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

print("Addition:")
print(np.add(arr1, arr2))

print("\nSubtraction:")
print(np.subtract(arr1, arr2))

print("\nMultiplication:")
print(np.multiply(arr1, arr2))

print("\nDivision:")
print(np.divide(arr1, arr2))

print("\nPower:")
print(np.power(arr2, 2))

print("\nModulus:")
print(np.mod(arr1, arr2))

print("\nRemainder:")
print(np.remainder(arr1, arr2))

print("\nDivmod:")
quotient, remainder = np.divmod(arr1, arr2)
print("Quotient:", quotient)
print("Remainder:", remainder)

print("\nAbsolute:")
print(np.absolute([-10, -5, 7, -2]))

Addition:
[12 24 35]

Subtraction:
[ 8 16 25]

Multiplication:
[ 20  80 150]

Division:
[5. 5. 6.]

Power:
[ 4 16 25]

Modulus:
[0 0 0]

Remainder:
[0 0 0]

Divmod:
Quotient: [5 5 6]
Remainder: [0 0 0]

Absolute:
[10  5  7  2]


## NumPy ufunc Rounding Decimals

### What is Rounding?

- Converts decimal numbers according to different rounding rules.

### Functions

- `np.trunc()` → Removes decimal part.
- `np.fix()` → Same as `trunc()`.
- `np.around()` → Rounds to nearest value.
- `np.floor()` → Always rounds down.
- `np.ceil()` → Always rounds up.

### Examples

```python
np.trunc(3.75)      # 3
np.fix(3.75)        # 3
np.around(3.56, 1)  # 3.6
np.floor(3.9)       # 3
np.ceil(3.2)        # 4
```

### Best Practice

- Use `around()` for normal rounding.
- Use `floor()` when you always need the lower integer.
- Use `ceil()` when you always need the higher integer.

In [ ]:
import numpy as np

numbers = np.array([3.75, 2.19, -4.89, 5.56])

# ==========================================
# Trunc
# ==========================================
print("Trunc:")
print(np.trunc(numbers))

# ==========================================
# Fix
# ==========================================
print("\nFix:")
print(np.fix(numbers))

# ==========================================
# Around
# ==========================================
print("\nAround:")
print(np.around(numbers))

print("\nAround (2 Decimal Places):")
print(np.around(numbers, 2))

# ==========================================
# Floor
# ==========================================
print("\nFloor:")
print(np.floor(numbers))

# ==========================================
# Ceil
# ==========================================
print("\nCeil:")
print(np.ceil(numbers))

Trunc:
[ 3.  2. -4.  5.]

Fix:
[ 3.  2. -4.  5.]

Around:
[ 4.  2. -5.  6.]

Around (2 Decimal Places):
[ 3.75  2.19 -4.89  5.56]

Floor:
[ 3.  2. -5.  5.]

Ceil:
[ 4.  3. -4.  6.]


## NumPy ufunc Logs

### What is a Logarithm?

- A logarithm tells us the power needed to get a number from a base.

### Functions

- `np.log2()` → Base 2 Log
- `np.log10()` → Base 10 Log
- `np.log()` → Natural Log (Base e)

### Examples

```python
np.log2(8)      # 3
np.log10(100)   # 2
np.log(10)      # 2.3025
```

### Uses

- Machine Learning
- Data Science
- Statistics
- Scientific Computing

### Best Practice

- Use `log2()` for binary calculations.
- Use `log10()` for decimal calculations.
- Use `log()` for natural logarithms.

In [ ]:
import numpy as np

numbers = np.array([2, 4, 8, 16])

# ==========================================
# Base 2 Log
# ==========================================

print("Log Base 2:")
print(np.log2(numbers))

# ==========================================
# Base 10 Log
# ==========================================

print("\nLog Base 10:")
print(np.log10([10, 100, 1000]))

# ==========================================
# Natural Log
# ==========================================

print("\nNatural Log:")
print(np.log([1, 2, 10]))

Log Base 2:
[1. 2. 3. 4.]

Log Base 10:
[1. 2. 3.]

Natural Log:
[0.         0.69314718 2.30258509]


## NumPy ufunc Summations

### What is Summation?

- Adds all elements of an array.
- Returns the total sum.

### Functions

- `np.sum()` → Returns total sum.
- `np.cumsum()` → Returns cumulative (running) sum.

### Axis

- `axis=0` → Column-wise sum.
- `axis=1` → Row-wise sum.

### Examples

```python
np.sum(arr)
np.sum(arr, axis=0)
np.sum(arr, axis=1)
np.cumsum(arr)
```

### Best Practice

- Use `sum()` for the final total.
- Use `cumsum()` when you need the running total.

In [ ]:
import numpy as np

# ==========================================
# Sum of One Array
# ==========================================

arr = np.array([10, 20, 30])

print("Sum:")
print(np.sum(arr))

# ==========================================
# Sum of Two Arrays
# ==========================================

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print("\nSum of Two Arrays:")
print(np.sum([arr1, arr2]))

# ==========================================
# Axis Example
# ==========================================

matrix = np.array([
    [1, 2],
    [3, 4]
])

print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))

print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

# ==========================================
# Cumulative Sum
# ==========================================

numbers = np.array([10, 20, 30, 40])

print("\nCumulative Sum:")
print(np.cumsum(numbers))

Sum:
60

Sum of Two Arrays:
66

Column-wise Sum:
[4 6]

Row-wise Sum:
[3 7]

Cumulative Sum:
[ 10  30  60 100]


## NumPy ufunc Products

### What is Product?

- Multiplies all elements of an array.
- Returns the final multiplication result.

### Functions

- `np.prod()` → Returns total product.
- `np.cumprod()` → Returns cumulative (running) product.

### Axis

- `axis=0` → Column-wise product.
- `axis=1` → Row-wise product.

### Examples

```python
np.prod(arr)
np.prod(arr, axis=0)
np.prod(arr, axis=1)
np.cumprod(arr)
```

### Best Practice

- Use `prod()` for the final multiplication result.
- Use `cumprod()` when you need the running product.

In [ ]:
import numpy as np

# ==========================================
# Product of One Array
# ==========================================

arr = np.array([2, 3, 4])

print("Product:")
print(np.prod(arr))

# ==========================================
# Product of Two Arrays
# ==========================================

arr1 = np.array([2, 3])
arr2 = np.array([4, 5])

print("\nProduct of Two Arrays:")
print(np.prod([arr1, arr2]))

# ==========================================
# Axis Example
# ==========================================

matrix = np.array([
    [2, 3],
    [4, 5]
])

print("\nColumn-wise Product:")
print(np.prod(matrix, axis=0))

print("\nRow-wise Product:")
print(np.prod(matrix, axis=1))

# ==========================================
# Cumulative Product
# ==========================================

numbers = np.array([2, 3, 4, 5])

print("\nCumulative Product:")
print(np.cumprod(numbers))

Product:
24

Product of Two Arrays:
120

Column-wise Product:
[ 8 15]

Row-wise Product:
[ 6 20]

Cumulative Product:
[  2   6  24 120]


## NumPy ufunc Differences

### What is Difference?

- Finds the difference between consecutive elements.
- Uses subtraction.
- Output size becomes one element smaller.

### Function

- `np.diff()` → Returns the difference between consecutive elements.

### Parameter

- `n=1` → Difference once (default).
- `n=2` → Difference of the first difference.
- `n=3` → Difference three times.

### Examples

```python
np.diff(arr)
np.diff(arr, n=2)
np.diff(arr, n=3)
```

### Best Practice

- Use `np.diff()` to analyze changes between consecutive values.

In [ ]:
import numpy as np

numbers = np.array([10, 15, 25, 40])

# ==========================================
# First Difference
# ==========================================

print("First Difference:")
print(np.diff(numbers))

# ==========================================
# Second Difference
# ==========================================

print("\nSecond Difference:")
print(np.diff(numbers, n=2))

# ==========================================
# Third Difference
# ==========================================

print("\nThird Difference:")
print(np.diff(numbers, n=3))

First Difference:
[ 5 10 15]

Second Difference:
[5 5]

Third Difference:
[0]


## NumPy ufunc Finding LCM

### What is LCM?

- LCM stands for Least Common Multiple.
- It is the smallest number divisible by all given numbers.

### Functions

- `np.lcm(a, b)` → Finds the LCM of two numbers or arrays.
- `np.lcm.reduce(arr)` → Finds the LCM of multiple numbers.

### Examples

```python
np.lcm(4, 6)
np.lcm.reduce([3, 6, 9])
```

### Best Practice

- Use `np.lcm()` for two values.
- Use `np.lcm.reduce()` for multiple values.

In [ ]:
import numpy as np

# ==========================================
# LCM of Two Numbers
# ==========================================

print("LCM of 4 and 6:")
print(np.lcm(4, 6))

# ==========================================
# LCM of Two Arrays
# ==========================================

arr1 = np.array([4, 6, 8])
arr2 = np.array([2, 3, 4])

print("\nLCM of Arrays:")
print(np.lcm(arr1, arr2))

# ==========================================
# LCM of Multiple Numbers
# ==========================================

numbers = np.array([3, 6, 9])

print("\nLCM of Multiple Numbers:")
print(np.lcm.reduce(numbers))

LCM of 4 and 6:
12

LCM of Arrays:
[4 6 8]

LCM of Multiple Numbers:
18


## NumPy ufunc Finding GCD

### What is GCD?

- GCD stands for Greatest Common Divisor.
- Also called HCF (Highest Common Factor).
- It is the largest number that divides all given numbers.

### Functions

- `np.gcd(a, b)` → Finds the GCD of two numbers or arrays.
- `np.gcd.reduce(arr)` → Finds the GCD of multiple numbers.

### Examples

```python
np.gcd(12, 16)
np.gcd.reduce([12, 24, 36])
```

### Best Practice

- Use `np.gcd()` for two values.
- Use `np.gcd.reduce()` for multiple values.

In [ ]:
import numpy as np

# ==========================================
# GCD of Two Numbers
# ==========================================

print("GCD of 12 and 16:")
print(np.gcd(12, 16))

# ==========================================
# GCD of Two Arrays
# ==========================================

arr1 = np.array([12, 18, 20])
arr2 = np.array([8, 6, 10])

print("\nGCD of Arrays:")
print(np.gcd(arr1, arr2))

# ==========================================
# GCD of Multiple Numbers
# ==========================================

numbers = np.array([12, 24, 36])

print("\nGCD of Multiple Numbers:")
print(np.gcd.reduce(numbers))

GCD of 12 and 16:
4

GCD of Arrays:
[ 4  6 10]

GCD of Multiple Numbers:
12


## NumPy ufunc Trigonometric

### What are Trigonometric Functions?

- Used for angle calculations.
- NumPy uses radians by default.

### Conversion Functions

- `np.deg2rad()` → Degree to Radian.
- `np.rad2deg()` → Radian to Degree.

### Trigonometric Functions

- `np.sin()` → Sine
- `np.cos()` → Cosine
- `np.tan()` → Tangent

### Inverse Functions

- `np.arcsin()`
- `np.arccos()`
- `np.arctan()`

### Examples

```python
np.sin(np.deg2rad(90))
np.cos(np.deg2rad(60))
np.tan(np.deg2rad(45))
```

### Best Practice

- Convert degrees to radians before using `sin()`, `cos()`, or `tan()`.

In [ ]:
import numpy as np

# ==========================================
# Degree to Radian
# ==========================================

angle = 90

radian = np.deg2rad(angle)

print("Radian:")
print(radian)

# ==========================================
# Radian to Degree
# ==========================================

print("\nDegree:")
print(np.rad2deg(radian))

# ==========================================
# Trigonometric Functions
# ==========================================

print("\nSin 90°:")
print(np.sin(np.deg2rad(90)))

print("\nCos 60°:")
print(np.cos(np.deg2rad(60)))

print("\nTan 45°:")
print(np.tan(np.deg2rad(45)))

# ==========================================
# Using Arrays
# ==========================================

angles = np.array([0, 30, 45, 60, 90])

radians = np.deg2rad(angles)

print("\nSin Values:")
print(np.sin(radians))

# ==========================================
# Inverse Trigonometric Function
# ==========================================

print("\nInverse Sin:")
print(np.rad2deg(np.arcsin(1)))

Radian:
1.5707963267948966

Degree:
90.0

Sin 90°:
1.0

Cos 60°:
0.5000000000000001

Tan 45°:
0.9999999999999999

Sin Values:
[0.         0.5        0.70710678 0.8660254  1.        ]

Inverse Sin:
90.0


## NumPy ufunc Hyperbolic

### What are Hyperbolic Functions?

- Similar to trigonometric functions.
- Used in mathematics, engineering, and machine learning.
- Work with radian values.

### Hyperbolic Functions

- `np.sinh()` → Hyperbolic Sine
- `np.cosh()` → Hyperbolic Cosine
- `np.tanh()` → Hyperbolic Tangent

### Inverse Hyperbolic Functions

- `np.arcsinh()` → Inverse Hyperbolic Sine
- `np.arccosh()` → Inverse Hyperbolic Cosine
- `np.arctanh()` → Inverse Hyperbolic Tangent

### Examples

```python
np.sinh(np.pi/2)
np.cosh(np.pi/2)
np.tanh(np.pi/2)
```

### Best Practice

- Use radian values.
- `arccosh()` accepts values ≥ 1.
- `arctanh()` accepts values between -1 and 1.

In [ ]:
import numpy as np

# ==========================================
# Hyperbolic Functions
# ==========================================

print("Sinh:")
print(np.sinh(np.pi / 2))

print("\nCosh:")
print(np.cosh(np.pi / 2))

print("\nTanh:")
print(np.tanh(np.pi / 2))

# ==========================================
# Using Arrays
# ==========================================

values = np.array([0, 1, 2])

print("\nSinh of Array:")
print(np.sinh(values))

print("\nCosh of Array:")
print(np.cosh(values))

print("\nTanh of Array:")
print(np.tanh(values))

# ==========================================
# Inverse Hyperbolic Functions
# ==========================================

print("\nArcsinh:")
print(np.arcsinh(1))

print("\nArccosh:")
print(np.arccosh(2))

print("\nArctanh:")
print(np.arctanh(0.5))

Sinh:
2.3012989023072947

Cosh:
2.5091784786580567

Tanh:
0.9171523356672744

Sinh of Array:
[0.         1.17520119 3.62686041]

Cosh of Array:
[1.         1.54308063 3.76219569]

Tanh of Array:
[0.         0.76159416 0.96402758]

Arcsinh:
0.881373587019543

Arccosh:
1.3169578969248166

Arctanh:
0.5493061443340548


## NumPy ufunc Set Operations

### What are Set Operations?

- Used to compare arrays.
- Help find unique, common, and different values.

### Functions

- `np.unique()` → Removes duplicate values.
- `np.union1d()` → Combines unique values from two arrays.
- `np.intersect1d()` → Finds common values.
- `np.setdiff1d()` → Finds values in the first array that are not in the second.
- `np.setxor1d()` → Finds values that are different in both arrays.

### Examples

```python
np.unique(arr)
np.union1d(arr1, arr2)
np.intersect1d(arr1, arr2)
np.setdiff1d(arr1, arr2)
np.setxor1d(arr1, arr2)
```

### Best Practice

- Use `unique()` to remove duplicates.
- Use `intersect1d()` to find common values.
- Use `union1d()` to merge unique values.

In [ ]:
import numpy as np

arr = np.array([1, 2, 2, 3, 4, 4, 5])

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

# ==========================================
# Unique Values
# ==========================================

print("Unique Values:")
print(np.unique(arr))

# ==========================================
# Union
# ==========================================

print("\nUnion:")
print(np.union1d(arr1, arr2))

# ==========================================
# Intersection
# ==========================================

print("\nIntersection:")
print(np.intersect1d(arr1, arr2))

# ==========================================
# Difference
# ==========================================

print("\nDifference (arr1 - arr2):")
print(np.setdiff1d(arr1, arr2))

# ==========================================
# Symmetric Difference
# ==========================================

print("\nSymmetric Difference:")
print(np.setxor1d(arr1, arr2))

Unique Values:
[1 2 3 4 5]

Union:
[1 2 3 4 5 6]

Intersection:
[3 4]

Difference (arr1 - arr2):
[1 2]

Symmetric Difference:
[1 2 5 6]
