## NumPy Introduction

### What is NumPy?

- NumPy stands for **Numerical Python**.
- It is a Python library.
- It is used for numerical computing.
- It provides fast and efficient arrays.

### Features

- Fast array processing
- Mathematical operations
- Matrix operations
- Statistics
- Linear algebra
- Random number generation

### Why Use NumPy?

- Faster than Python lists
- Uses less memory
- Optimized for numerical calculations
- Widely used in AI, ML, and Data Science

### Why is NumPy Fast?

- Written mainly in C.
- Stores data in contiguous memory.
- Performs optimized operations on arrays.

### NumPy Arrays

- The main data structure in NumPy is the array.
- Arrays are faster than Python lists for numerical work.

### Installation

```bash
pip install numpy
```

### Import NumPy

```python
import numpy as np
```

### Check Version

```python
print(np.__version__)
```

### Create an Array

```python
numbers = np.array([10, 20, 30])
```

### Python List vs NumPy Array

| Python List | NumPy Array |
|--------------|-------------|
| Built-in | NumPy library |
| Slower | Faster |
| More memory | Less memory |
| General purpose | Numerical computing |

### Best Practice

- Import NumPy using:

```python
import numpy as np
```

- Use NumPy arrays for numerical and scientific computing.

In [ ]:
import numpy as np

#checking its version
print("Numpy version: ",np.__version__)

print("-------------------")

numbers=np.array([10,20,37,58])
print("Numy Array")
print(numbers)


print("-------------------")

python_list=[18,38,59,37,579]

numpy_array=np.array([23,85,43,56,68])

print("Python List:",python_list)
print("Python Array:",numpy_array)

print("-------------------")

#Array type
print(type(numpy_array))


Numpy version:  2.0.2
-------------------
Numy Array
[10 20 37 58]
-------------------
Python List: [18, 38, 59, 37, 579]
Python Array: [23 85 43 56 68]
-------------------
<class 'numpy.ndarray'>


## NumPy Getting Started

### Install NumPy

- Install NumPy using `pip`.

Command:

```bash
pip install numpy
```

### Google Colab

- NumPy is pre-installed in Google Colab.
- No installation is usually required.

### Import NumPy

```python
import numpy as np
```

### Alias

- `np` is the standard alias for NumPy.
- It makes code shorter and easier to read.

### Without Alias

```python
import numpy

numbers = numpy.array([1,2,3])
```

### With Alias

```python
import numpy as np

numbers = np.array([1,2,3])
```

### Check Version

```python
print(np.__version__)
```

### Create First Array

```python
numbers = np.array([10,20,30])
```

### Print Array

```python
print(numbers)
```

### Best Practice

- Always import NumPy using:

```python
import numpy as np
```

- Use `np.array()` to create NumPy arrays.

## NumPy Creating Arrays

### Create an Array

- NumPy uses the `array()` function to create arrays.

Syntax:

```python
np.array(data)
```

### 0-D Array

- Contains a single value.
- Also called a scalar.

Example:

```python
np.array(42)
```

### 1-D Array

- Contains one list.
- Most common type of array.

Example:

```python
np.array([10,20,30])
```

### 2-D Array

- Contains nested lists.
- Represents rows and columns.

Example:

```python
np.array([
    [1,2],
    [3,4]
])
```

### 3-D Array

- Contains multiple 2-D arrays.

Example:

```python
np.array([
[
[1,2],
[3,4]
],
[
[5,6],
[7,8]
]
])
```

### Check Dimensions

```python
arr.ndim
```

### Higher Dimensional Arrays

- NumPy supports arrays with more than 3 dimensions.

### `ndmin`

- Sets the minimum number of dimensions.

Example:

```python
np.array([1,2,3], ndmin=3)
```

### Best Practice

- Use 1D arrays for simple lists.
- Use 2D arrays for tables.
- Use 3D arrays for collections of tables or images.

In [ ]:
import numpy as np

# 0D Array
arr0=np.array(100)
print(arr0)
print("Dimensions:",arr0.ndim)
print("----------------------")


# 1D Array
arr1 = np.array([10,28,37,48])
print(arr1)
print("Dimensions:",arr1.ndim)
print("----------------------")

# 2D Array
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print("Dimensions:", arr2.ndim)

print("----------------------")

# 3D Array
arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)
print("Dimensions:", arr3.ndim)

print("----------------------")

# ndmin Example
arr = np.array([1, 2, 3], ndmin=5)

print(arr)
print("Dimensions:", arr.ndim)

100
Dimensions: 0
----------------------
[10 28 37 48]
Dimensions: 1
----------------------
[[1 2 3]
 [4 5 6]]
Dimensions: 2
----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
----------------------
[[[[[1 2 3]]]]]
Dimensions: 5


## NumPy Array Indexing

### What is Indexing?

- Indexing is used to access specific elements in an array.
- NumPy indexing starts from `0`.

### 1D Indexing

Syntax:

```python
arr[index]
```

Example:

```python
arr = np.array([10,20,30])

print(arr[0])
```

### Negative Indexing

- Negative indexing starts from the end.

Example:

```python
arr[-1]
```

returns the last element.

### 2D Indexing

Syntax:

```python
arr[row, column]
```

Example:

```python
arr[1,2]
```

### 3D Indexing

Syntax:

```python
arr[layer, row, column]
```

Example:

```python
arr[0,1,1]
```

### Best Practice

- Remember indexing starts from `0`.
- For 2D arrays, always think **Row → Column**.
- For 3D arrays, think **Layer → Row → Column**.

In [ ]:
import numpy as np


# 1D Indexing


arr1 = np.array([10, 20, 30, 40])

print("First Element :", arr1[0])
print("Second Element:", arr1[1])
print("Last Element  :", arr1[-1])

print("----------------------")


# Sum of Elements

arr = np.array([1, 2, 3, 4])

print("Sum:", arr[2] + arr[3])

print("----------------------")


# 2D Indexing

arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr2)

print("Row 0, Column 1:", arr2[0, 1])
print("Row 1, Column 2:", arr2[1, 2])

print("----------------------")


# 3D Indexing

arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)

print("Layer 0, Row 1, Column 1:", arr3[0, 1, 1])
print("Layer 1, Row 0, Column 1:", arr3[1, 0, 1])

First Element : 10
Second Element: 20
Last Element  : 40
----------------------
Sum: 7
----------------------
[[10 20 30]
 [40 50 60]]
Row 0, Column 1: 20
Row 1, Column 2: 60
----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Layer 0, Row 1, Column 1: 4
Layer 1, Row 0, Column 1: 6


## NumPy Array Slicing

### What is Slicing?

- Slicing is used to access a portion of an array.
- It returns multiple elements.

### Basic Syntax

```python
arr[start:stop]
```

- Start index is included.
- Stop index is excluded.

### Examples

```python
arr[1:4]
```

```python
arr[:3]
```

```python
arr[2:]
```

```python
arr[:]
```

### Negative Slicing

```python
arr[-3:-1]
```

### Step

Syntax:

```python
arr[start:stop:step]
```

Example:

```python
arr[::2]
```

### Reverse Array

```python
arr[::-1]
```

### 2D Slicing

Single row:

```python
arr[0,1:3]
```

All rows:

```python
arr[:,1]
```

Multiple columns:

```python
arr[:,1:3]
```

### Best Practice

- Remember:
  - Start is included.
  - Stop is excluded.
- Use `:` to select all rows or all columns.

In [ ]:
import numpy as np

# ==========================================
# Create 1D Array
# ==========================================

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(arr)

print("----------------------")

# Slice from index 1 to 3
print(arr[1:4])

# From beginning to index 2
print(arr[:3])

# From index 2 to end
print(arr[2:])

# Complete array
print(arr[:])

print("----------------------")

# Negative slicing
print(arr[-3:-1])

print("----------------------")

# Step
print(arr[::2])

print("----------------------")

# Reverse
print(arr[::-1])

print("----------------------")

# ==========================================
# 2D Array
# ==========================================

arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

print(arr2)

print("----------------------")

# First row
print(arr2[0,1:3])

# Second row
print(arr2[1,0:2])

# Second column
print(arr2[:,1])

# Column slice
print(arr2[:,1:3])

Original Array:
[10 20 30 40 50]
----------------------
[20 30 40]
[10 20 30]
[30 40 50]
[10 20 30 40 50]
----------------------
[30 40]
----------------------
[10 30 50]
----------------------
[50 40 30 20 10]
----------------------
[[1 2 3 4]
 [5 6 7 8]]
----------------------
[2 3]
[5 6]
[2 6]
[[2 3]
 [6 7]]


## NumPy Data Types

### What is a Data Type?

- A data type defines the type of values stored in an array.
- Every NumPy array has a data type.

### Check Data Type

```python
print(arr.dtype)
```

### Common Data Type Codes

| Code | Meaning |
|------|---------|
| `i` | Integer |
| `f` | Float |
| `b` | Boolean |
| `U` | Unicode String |
| `S` | Byte String |
| `O` | Object |

### Set Data Type

```python
arr = np.array([1,2,3], dtype="f")
```

### Convert Data Type

```python
new_arr = arr.astype(float)
```

### Common Conversions

- Integer → Float
- Float → Integer
- Integer → Boolean
- Boolean → Integer

### Best Practice

- Use `arr.dtype` to check the data type.
- Use `astype()` to convert data types safely.
- Make sure the values can actually be converted.

In [ ]:
import numpy as np

# ==========================================
# Integer Array
# ==========================================

arr1 = np.array([10, 20, 30])

print(arr1)
print("Data Type:", arr1.dtype)

print("----------------------")

# ==========================================
# Float Array
# ==========================================

arr2 = np.array([10.5, 20.2, 30.8])

print(arr2)
print("Data Type:", arr2.dtype)

print("----------------------")

# ==========================================
# String Array
# ==========================================

arr3 = np.array(["Apple", "Mango", "Banana"])

print(arr3)
print("Data Type:", arr3.dtype)

print("----------------------")

# ==========================================
# Set Data Type
# ==========================================

arr4 = np.array([1, 2, 3], dtype="f")

print(arr4)
print("Data Type:", arr4.dtype)

print("----------------------")

# ==========================================
# Convert Integer to Float
# ==========================================

arr5 = np.array([10, 20, 30])

float_arr = arr5.astype(float)

print(float_arr)
print(float_arr.dtype)

print("----------------------")

# ==========================================
# Convert Float to Integer
# ==========================================

arr6 = np.array([1.5, 2.8, 3.9])

int_arr = arr6.astype(int)

print(int_arr)
print(int_arr.dtype)

print("----------------------")

# ==========================================
# Convert Integer to Boolean
# ==========================================

arr7 = np.array([1, 0, 5])

bool_arr = arr7.astype(bool)

print(bool_arr)
print(bool_arr.dtype)

[10 20 30]
Data Type: int64
----------------------
[10.5 20.2 30.8]
Data Type: float64
----------------------
['Apple' 'Mango' 'Banana']
Data Type: <U6
----------------------
[1. 2. 3.]
Data Type: float32
----------------------
[10. 20. 30.]
float64
----------------------
[1 2 3]
int64
----------------------
[ True False  True]
bool


## NumPy Array Shape

### What is Shape?

- Shape describes the size of each dimension.
- It tells how many elements exist in every dimension.

### Check Shape

```python
arr.shape
```

### 1D Shape

Example:

```python
arr = np.array([1,2,3,4])

print(arr.shape)
```

Output:

```text
(4,)
```

### 2D Shape

Example:

```python
arr = np.array([
[1,2,3],
[4,5,6]
])

print(arr.shape)
```

Output:

```text
(2,3)
```

### 3D Shape

Example:

```python
print(arr.shape)
```

Output:

```text
(2,2,2)
```

### `shape` vs `ndim`

| ndim | shape |
|------|--------|
| Number of dimensions | Size of each dimension |

### `ndmin`

```python
arr = np.array([1,2,3], ndmin=5)
```

Output:

```python
(1,1,1,1,3)
```

### Best Practice

- Use `arr.shape` to check the structure of an array.
- Use `arr.ndim` to check the number of dimensions.

In [1]:
import numpy as np

# ==========================================
# 1D Shape
# ==========================================

arr1 = np.array([10, 20, 30, 40])

print("1D Array:")
print(arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)

print("----------------------")

# ==========================================
# 2D Shape
# ==========================================

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)

print("----------------------")

# ==========================================
# 3D Shape
# ==========================================

arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)

print("----------------------")

# ==========================================
# ndmin Example
# ==========================================

arr4 = np.array([1, 2, 3], ndmin=5)

print(arr4)
print("Shape:", arr4.shape)
print("Dimensions:", arr4.ndim)

1D Array:
[10 20 30 40]
Shape: (4,)
Dimensions: 1
----------------------
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3
----------------------
[[[[[1 2 3]]]]]
Shape: (1, 1, 1, 1, 3)
Dimensions: 5


## NumPy Array Reshape

### What is Reshape?

- Changes the shape of an array.
- The data remains the same.
- Only the arrangement changes.

### Syntax

```python
arr.reshape(rows, columns)
```

### 1D to 2D

```python
arr.reshape(2,3)
```

### 1D to 3D

```python
arr.reshape(2,2,2)
```

### Rule

- Total number of elements must remain the same.

Example:

- `2 × 3 = 6` ✅
- `3 × 2 = 6` ✅
- `4 × 2 = 8` ❌ (if array has only 6 elements)

### Unknown Dimension

```python
arr.reshape(2,-1)
```

- `-1` lets NumPy calculate the missing dimension automatically.

### Best Practice

- Check the array shape before reshaping.
- Ensure the total number of elements does not change.

In [2]:
import numpy as np

# Original 1D Array
arr = np.array([1, 2, 3, 4, 5, 6])

print("Original Shape:", arr.shape)

# 1D -> 2D
arr2 = arr.reshape(2, 3)

print(arr2)
print("Shape:", arr2.shape)

print("------------------")

# 1D -> 3D
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

new_arr = arr3.reshape(2, 2, 2)

print(new_arr)
print("Shape:", new_arr.shape)

print("------------------")

# Using -1
auto_shape = arr.reshape(2, -1)

print(auto_shape)
print("Shape:", auto_shape.shape)

Original Shape: (6,)
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
------------------
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


## NumPy Array Iterating

### What is Iterating?

- Iterating means accessing each element of an array one by one.

### Iterate 1D Array

```python
for x in arr:
    print(x)
```

### Iterate 2D Array

```python
for row in arr:
    for value in row:
        print(value)
```

### Iterate 3D Array

- Use nested loops for each dimension.

### Using `np.nditer()`

```python
for x in np.nditer(arr):
    print(x)
```

- Works for arrays of any dimension.

### Using `np.ndenumerate()`

```python
for index, value in np.ndenumerate(arr):
    print(index, value)
```

- Returns both index and value.

### Best Practice

- Use normal `for` loop for simple 1D arrays.
- Use `np.nditer()` for arrays with multiple dimensions.
- Use `np.ndenumerate()` when you also need indexes.

In [3]:
import numpy as np

# ==========================================
# 1D Array
# ==========================================

arr1 = np.array([10, 20, 30])

print("1D Array:")
for x in arr1:
    print(x)

print("------------------")

# ==========================================
# 2D Array
# ==========================================

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
for row in arr2:
    for value in row:
        print(value)

print("------------------")

# ==========================================
# nditer()
# ==========================================

print("Using nditer:")
for x in np.nditer(arr2):
    print(x)

print("------------------")

# ==========================================
# ndenumerate()
# ==========================================

print("Using ndenumerate:")
for index, value in np.ndenumerate(arr2):
    print(index, value)

1D Array:
10
20
30
------------------
2D Array:
1
2
3
4
5
6
------------------
Using nditer:
1
2
3
4
5
6
------------------
Using ndenumerate:
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


## NumPy Array Join

### What is Join?

- Join combines two or more arrays into one array.

### concatenate()

```python
np.concatenate((arr1, arr2))
```

### axis

- `axis=0` → Join rows
- `axis=1` → Join columns

### stack()

```python
np.stack((arr1, arr2))
```

- Creates a new dimension.

### hstack()

```python
np.hstack((arr1, arr2))
```

- Horizontal join.

### vstack()

```python
np.vstack((arr1, arr2))
```

- Vertical join.

### dstack()

```python
np.dstack((arr1, arr2))
```

- Joins along the third dimension.

### Best Practice

- Use `concatenate()` for normal joining.
- Use `stack()` when you need an extra dimension.

In [4]:
import numpy as np

# ==========================================
# concatenate()
# ==========================================

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("concatenate():")
print(np.concatenate((arr1, arr2)))

print("------------------")

# ==========================================
# axis example
# ==========================================

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("axis=0")
print(np.concatenate((a, b), axis=0))

print()

print("axis=1")
print(np.concatenate((a, b), axis=1))

print("------------------")

# ==========================================
# stack()
# ==========================================

print("stack()")
print(np.stack((arr1, arr2)))

print("------------------")

# ==========================================
# hstack()
# ==========================================

print("hstack()")
print(np.hstack((arr1, arr2)))

print("------------------")

# ==========================================
# vstack()
# ==========================================

print("vstack()")
print(np.vstack((arr1, arr2)))

print("------------------")

# ==========================================
# dstack()
# ==========================================

print("dstack()")
print(np.dstack((arr1, arr2)))

concatenate():
[1 2 3 4 5 6]
------------------
axis=0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

axis=1
[[1 2 5 6]
 [3 4 7 8]]
------------------
stack()
[[1 2 3]
 [4 5 6]]
------------------
hstack()
[1 2 3 4 5 6]
------------------
vstack()
[[1 2 3]
 [4 5 6]]
------------------
dstack()
[[[1 4]
  [2 5]
  [3 6]]]


## NumPy Array Split

### What is Split?

- Split divides one array into multiple smaller arrays.

### array_split()

```python
np.array_split(arr, parts)
```

### Example

```python
parts = np.array_split(arr, 3)
```

### Access Individual Part

```python
parts[0]
```

### 2D Split

- By default, splits rows.

### hsplit()

```python
np.hsplit(arr, 2)
```

- Splits columns.

### vsplit()

```python
np.vsplit(arr, 2)
```

- Splits rows.

### Difference

- `split()` → Equal split only.
- `array_split()` → Equal or unequal split.

### Best Practice

- Prefer `array_split()` because it is more flexible.

In [5]:
import numpy as np

# ==========================================
# Split 1D Array
# ==========================================

arr = np.array([10, 20, 30, 40, 50, 60])

parts = np.array_split(arr, 3)

print("Split into 3 parts:")
print(parts)

print("------------------")

# Access first part
print("First Part:")
print(parts[0])

print("------------------")

# ==========================================
# Split 2D Array
# ==========================================

arr2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

print("2D Split:")
print(np.array_split(arr2, 2))

print("------------------")

# ==========================================
# Horizontal Split
# ==========================================

arr3 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("Horizontal Split:")
print(np.hsplit(arr3, 2))

print("------------------")

# ==========================================
# Vertical Split
# ==========================================

print("Vertical Split:")
print(np.vsplit(arr3, 2))

Split into 3 parts:
[array([10, 20]), array([30, 40]), array([50, 60])]
------------------
First Part:
[10 20]
------------------
2D Split:
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
------------------
Horizontal Split:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
------------------
Vertical Split:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


## NumPy Array Search

### What is Search?

- Search is used to find the index of values in an array.

### `np.where()`

```python
np.where(condition)
```

- Returns indexes where the condition is True.

### Search a Value

```python
np.where(arr == 20)
```

### Search Using Condition

```python
np.where(arr > 25)
```

### Search Even Numbers

```python
np.where(arr % 2 == 0)
```

### Search Odd Numbers

```python
np.where(arr % 2 == 1)
```

### Best Practice

- Remember that `np.where()` returns indexes, not values.
- It works with values as well as conditions.

In [6]:
import numpy as np

# ==========================================
# Search a Value
# ==========================================

arr = np.array([10, 20, 30, 20, 50])

print("Index of 20:")
print(np.where(arr == 20))

print("------------------")

# ==========================================
# Search Using Condition
# ==========================================

print("Values greater than 25:")
print(np.where(arr > 25))

print("------------------")

# ==========================================
# Even Numbers
# ==========================================

arr2 = np.array([1, 2, 3, 4, 5, 6])

print("Even Number Indexes:")
print(np.where(arr2 % 2 == 0))

print("------------------")

# ==========================================
# Odd Numbers
# ==========================================

print("Odd Number Indexes:")
print(np.where(arr2 % 2 == 1))

Index of 20:
(array([1, 3]),)
------------------
Values greater than 25:
(array([2, 4]),)
------------------
Even Number Indexes:
(array([1, 3, 5]),)
------------------
Odd Number Indexes:
(array([0, 2, 4]),)


## NumPy Array Sort

### What is Sorting?

- Sorting arranges data in order.
- By default, sorting is in ascending order.

### Syntax

```python
np.sort(arr)
```

### Sort Numbers

```python
np.sort(arr)
```

### Sort Strings

```python
np.sort(string_array)
```

### Sort Boolean Values

```python
np.sort(bool_array)
```

- `False` comes before `True`.

### Sort 2D Array

- Each row is sorted separately.

### Best Practice

- `np.sort()` returns a sorted copy.
- The original array remains unchanged.

In [7]:
import numpy as np

# ==========================================
# Sort Numbers
# ==========================================

arr1 = np.array([30, 10, 50, 20])

print("Sorted Numbers:")
print(np.sort(arr1))

print("Original Array:")
print(arr1)

print("------------------")

# ==========================================
# Sort Strings
# ==========================================

arr2 = np.array(["Mango", "Apple", "Banana"])

print("Sorted Strings:")
print(np.sort(arr2))

print("------------------")

# ==========================================
# Sort Boolean Values
# ==========================================

arr3 = np.array([True, False, True])

print("Sorted Boolean:")
print(np.sort(arr3))

print("------------------")

# ==========================================
# Sort 2D Array
# ==========================================

arr4 = np.array([
    [3, 2, 1],
    [6, 5, 4]
])

print("Sorted 2D Array:")
print(np.sort(arr4))

Sorted Numbers:
[10 20 30 50]
Original Array:
[30 10 50 20]
------------------
Sorted Strings:
['Apple' 'Banana' 'Mango']
------------------
Sorted Boolean:
[False  True  True]
------------------
Sorted 2D Array:
[[1 2 3]
 [4 5 6]]


## NumPy Filter Array

### What is Filtering?

- Filtering selects values based on a condition.
- It returns only the values that satisfy the condition.

### Boolean Mask

- A Boolean mask contains `True` and `False`.
- `True` → Select the value.
- `False` → Ignore the value.

### Filter Using Condition

```python
arr[arr > 30]
```

### Filter Even Numbers

```python
arr[arr % 2 == 0]
```

### Filter Odd Numbers

```python
arr[arr % 2 == 1]
```

### Custom Boolean Mask

```python
mask = [True, False, True, False]

arr[mask]
```

### `where()` vs Filtering

- `np.where()` → Returns indexes.
- Filtering → Returns values.

### Best Practice

- Use filtering when you need the actual data.
- Use `np.where()` when you need the indexes.

In [8]:
import numpy as np

# ==========================================
# Original Array
# ==========================================

arr = np.array([10, 20, 30, 40, 50])

# Filter values greater than 30
print("Values > 30:")
print(arr[arr > 30])

print("------------------")

# ==========================================
# Even Numbers
# ==========================================

arr2 = np.array([1, 2, 3, 4, 5, 6])

print("Even Numbers:")
print(arr2[arr2 % 2 == 0])

print("------------------")

# ==========================================
# Odd Numbers
# ==========================================

print("Odd Numbers:")
print(arr2[arr2 % 2 == 1])

print("------------------")

# ==========================================
# Boolean Mask
# ==========================================

arr3 = np.array([10, 20, 30, 40])

mask = [True, False, True, False]

print("Filtered with Boolean Mask:")
print(arr3[mask])

Values > 30:
[40 50]
------------------
Even Numbers:
[2 4 6]
------------------
Odd Numbers:
[1 3 5]
------------------
Filtered with Boolean Mask:
[10 30]
